name: Build and Push Docker Image

on:
  push:

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    steps:
      - name: putting code on runner
        run: git clone https://github.com/Samairah369/git-action28.git

      - name: Build a docker image
        run: |
          cd git-action28
          docker build -t mynewimage:latest .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Tag and push the image
        run: |
          docker tag mynewimage:latest ${{ secrets.DOCKER_HUB_USERNAME }}/mynewimage:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mynewimage:latest
